### ISSUE TITLE
Suport for custom commit message

### ISSUE THREAD

**Issue by lobodpav** [dipien/semantic-version-gradle-plugin#34]
When using [Conventional Commit](https://www.conventionalcommits.org) checks in GitHub workflow actions, they always fail because this plugin generates commits that are not compliant.

It would be nice if the commit message prefix could be customised.

**Comment by maxirosson** [comment]
Since v1.4.0 you can configure the commit message adding a prefix with the `commitMessagePrefix` option. For example

```
./gradlew incrementVersion --commitMessagePrefix="[my prefix] " --versionIncrementType=MAJOR --versionIncrementBranch=master
```

**Comment by lobodpav** [comment]
Thanks a lot!
