### ISSUE TITLE
maximumVersion parameter isn't working

### ISSUE THREAD

**Issue by zloyMakar0n** [dipien/semantic-version-gradle-plugin#39]
An attempt to set a `maximumVersion` over default 99 value don't work and leads to error or unexpected behavior depending on specific case.

Unexpected behavior case:
1. In root `build.gradle` set `ext.maximumVersion="999"` and `version = "1.0.99"`
2. Run `./gradlew incrementVersion --versionIncrementType=PATCH`
3. See `version = "1.1.0"` in root `build.gradle` instead `version = "1.0.100"`

Error case:
1. In root `build.gradle` set `ext.maximumVersion="999"` and `version = "1.0.100"`
2. Run `./gradlew refresh`
3. See error: 

> * What went wrong:
> A problem occurred evaluating root project 'new-project'.
>   Failed to apply plugin 'com.dipien.semantic-version'.
>      The version patch [100] should be a number between 0 and 99

After digging into source code I found that the reason might be in using `constructor(version: String)` of `Version` (which does not allow to override `maximumVersion`, but contain validation of `baseVersion`) in `SemanticVersionGradlePlugin` `apply()`-method and in `IncrementVersionHelper` `increment()`-method.

**Comment by maxirosson** [comment]
Released v1.4.1 with this fix. Thanks for reporting this !!!
